// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqiqgexsjnmifqfrctce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaXFnZXhzam5taWZxZnJjdGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTY0NTEsImV4cCI6MjA2NTU5MjQ1MX0.ppyp_6p1xf3gNpuHkvfapmZPwwwZJeJ9jhbKdgxUOy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);